//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertNumberApp.ConvertWebApp {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConvertWebApp.ConvertToWordSoap")]
    public interface ConvertToWordSoap {
        
        // CODEGEN: Generating message contract since element name number from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertNumberToWords", ReplyAction="*")]
        ConvertNumberApp.ConvertWebApp.ConvertNumberToWordsResponse ConvertNumberToWords(ConvertNumberApp.ConvertWebApp.ConvertNumberToWordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertNumberToWords", ReplyAction="*")]
        System.Threading.Tasks.Task<ConvertNumberApp.ConvertWebApp.ConvertNumberToWordsResponse> ConvertNumberToWordsAsync(ConvertNumberApp.ConvertWebApp.ConvertNumberToWordsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertNumberToWordsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertNumberToWords", Namespace="http://tempuri.org/", Order=0)]
        public ConvertNumberApp.ConvertWebApp.ConvertNumberToWordsRequestBody Body;
        
        public ConvertNumberToWordsRequest() {
        }
        
        public ConvertNumberToWordsRequest(ConvertNumberApp.ConvertWebApp.ConvertNumberToWordsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertNumberToWordsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string number;
        
        public ConvertNumberToWordsRequestBody() {
        }
        
        public ConvertNumberToWordsRequestBody(string number) {
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertNumberToWordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertNumberToWordsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConvertNumberApp.ConvertWebApp.ConvertNumberToWordsResponseBody Body;
        
        public ConvertNumberToWordsResponse() {
        }
        
        public ConvertNumberToWordsResponse(ConvertNumberApp.ConvertWebApp.ConvertNumberToWordsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertNumberToWordsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConvertNumberToWordsResult;
        
        public ConvertNumberToWordsResponseBody() {
        }
        
        public ConvertNumberToWordsResponseBody(string ConvertNumberToWordsResult) {
            this.ConvertNumberToWordsResult = ConvertNumberToWordsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConvertToWordSoapChannel : ConvertNumberApp.ConvertWebApp.ConvertToWordSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConvertToWordSoapClient : System.ServiceModel.ClientBase<ConvertNumberApp.ConvertWebApp.ConvertToWordSoap>, ConvertNumberApp.ConvertWebApp.ConvertToWordSoap {
        
        public ConvertToWordSoapClient() {
        }
        
        public ConvertToWordSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConvertToWordSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertToWordSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertToWordSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConvertNumberApp.ConvertWebApp.ConvertNumberToWordsResponse ConvertNumberApp.ConvertWebApp.ConvertToWordSoap.ConvertNumberToWords(ConvertNumberApp.ConvertWebApp.ConvertNumberToWordsRequest request) {
            return base.Channel.ConvertNumberToWords(request);
        }
        
        public string ConvertNumberToWords(string number) {
            ConvertNumberApp.ConvertWebApp.ConvertNumberToWordsRequest inValue = new ConvertNumberApp.ConvertWebApp.ConvertNumberToWordsRequest();
            inValue.Body = new ConvertNumberApp.ConvertWebApp.ConvertNumberToWordsRequestBody();
            inValue.Body.number = number;
            ConvertNumberApp.ConvertWebApp.ConvertNumberToWordsResponse retVal = ((ConvertNumberApp.ConvertWebApp.ConvertToWordSoap)(this)).ConvertNumberToWords(inValue);
            return retVal.Body.ConvertNumberToWordsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConvertNumberApp.ConvertWebApp.ConvertNumberToWordsResponse> ConvertNumberApp.ConvertWebApp.ConvertToWordSoap.ConvertNumberToWordsAsync(ConvertNumberApp.ConvertWebApp.ConvertNumberToWordsRequest request) {
            return base.Channel.ConvertNumberToWordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConvertNumberApp.ConvertWebApp.ConvertNumberToWordsResponse> ConvertNumberToWordsAsync(string number) {
            ConvertNumberApp.ConvertWebApp.ConvertNumberToWordsRequest inValue = new ConvertNumberApp.ConvertWebApp.ConvertNumberToWordsRequest();
            inValue.Body = new ConvertNumberApp.ConvertWebApp.ConvertNumberToWordsRequestBody();
            inValue.Body.number = number;
            return ((ConvertNumberApp.ConvertWebApp.ConvertToWordSoap)(this)).ConvertNumberToWordsAsync(inValue);
        }
    }
}
